### ISSUE TITLE
resolving bugs and adding new features

### ISSUE THREAD

**Issue by nichroot** [sh1zicus/dots-hyprland#1]
hey! just wanted to ask you if you were doing good :)

**Comment by nichroot** [comment]
wait nvm just saw you already have it in the config, switching rn! i hope the installer is functional right?

**Comment by sh1zicus** [comment]
> wait nvm just saw you already have it in the config, switching rn! i hope the installer is functional right?

Yes, I added it, everything works fine, the config has already changed quite a lot from the end-4 branch, I also collected useful pull requests that have not yet been added to end-4 dots, there’s a lot of stuff there, but I added: icons for turning on/off the sound/microphone, power-profiles, optimized the scripts a little, added a script that makes development easier (I change it in the repository directory and it replaces only the configs), removed unnecessary keyboard shortcuts and little things, added sound recording to the ffmpeg script, as I already said, the config will move further and further from the original, but I will adopt changes from the end-4 branch too, now I plan to write a more convenient and faster installation script

**Comment by nichroot** [comment]
so should I wait a bit more for the updated script or just use the current one?

**Comment by sh1zicus** [comment]
> so should I wait a bit more for the updated script or just use the current one?

I will most likely be able to start this business this weekend, now I have no free time, well, everything is working except for the new shadow config in hypr, yesterday I installed cachyos with gnome and then my dotfiles everything went without problems, the installation script was almost unchanged

you can clone the repository, backup your configs and replace

**Comment by nichroot** [comment]
Actually, I'm on a clean slate rn, just nuked my laptop 😓.. would you
recommend me just installing cachy with gnome and install using the script?

**Comment by nichroot** [comment]
![image](https://github.com/user-attachments/assets/130bb697-d661-49d9-8b47-5b83597bad65)
help me :(

**Comment by nichroot** [comment]
oh wait i get it, its because you haven't yet pushed the shadow fix in end's repo to yours.. didn't understand thats what you meant lol

**Comment by sh1zicus** [comment]
> bro 😭

???

**Comment by nichroot** [comment]
oh sorry, dont mind me im just dumb.. just saw now that you had fixed that

**Comment by nichroot** [comment]
where do i change the weather location?

**Comment by sh1zicus** [comment]
> where do i change the weather location?

```~/.config/ags/modules/.configuration/user_options.js ``` line 143

**Comment by nichroot** [comment]
whats the weather provider? like where do i search for the exact city near me

**Comment by sh1zicus** [comment]
> whats the weather provider? like where do i search for the exact city near me

wttr.in

if you open the site, it seems to recognize the nearest city itself

**Comment by nichroot** [comment]
thanks!

**Comment by nichroot** [comment]
lol the labels 😅, do you want me to close the issue?

**Comment by sh1zicus** [comment]
> lol the labels 😅, do you want me to close the issue?

if you find a bug or want to suggest some feature, create more 🙂

**Comment by nichroot** [comment]
can you help me re add the periodic table cheatsheet please? would be a great help. i tried doing it myself but got into some errors

**Comment by sh1zicus** [comment]
> can you help me re add the periodic table cheatsheet please? would be a great help. i tried doing it myself but got into some errors

I returned it in the  return-periodic-table branch I doubt its usefulness, 
consider it unnecessary, so it will not be in the main branch

**Comment by nichroot** [comment]
> > can you help me re add the periodic table cheatsheet please? would be a great help. i tried doing it myself but got into some errors
> 
> I returned it in the return-periodic-table branch I doubt its usefulness, consider it unnecessary, so it will not be in the main branch

ah thats okay, not that useful for me either but since im studying chemistry in class, it could come in handy at times.. thanks a lot for adding

**Comment by sh1zicus** [comment]
@emm-enn  I think the right way would be: create a new issue for a new problem,
otherwise everything can turn into a mess

**Comment by nichroot** [comment]
sorry won't repeat 🤕
