### ISSUE TITLE
[Feature] make toggle for dark/light mode for ags and gtk shell

### ISSUE THREAD

**Issue by PharmaRacist** [sh1zicus/dots-hyprland#10]
i have made simple toggle that change the gtk theme and i couldn't figure out how to change the ags mode can u edit this ?
`export const ModuleGtkModeToggle = async (props = {}) => {
  const button = Widget.Button({
    attribute: { enabled: false },
    className: "txt-small sidebar-iconbutton",
    tooltipText: getString("Toggle GTK Mode"),
    onClicked: async (self) => {
      self.attribute.enabled = !self.attribute.enabled;
      self.toggleClassName("sidebar-button-active", self.attribute.enabled);

      const mode = self.attribute.enabled ? "dark" : "light";

      // Set the GTK mode
      await execAsync(
        `gsettings set org.gnome.desktop.interface gtk-theme '${mode}-theme'`,
      ).catch(print);

      // Optional: Set additional adjustments for terminal, etc.
      // await execAsync(`command-for-terminal-adjustments-${mode}`).catch(print);
    },
    child: MaterialIcon("brightness_medium", "norm"),
    setup: (self) => {
      setupCursorHover(self);

      // Detect the current GTK mode
      const currentMode = exec(
        `gsettings get org.gnome.desktop.interface gtk-theme`,
      );
      self.attribute.enabled = currentMode.includes("dark");
      self.toggleClassName("sidebar-button-active", self.attribute.enabled);
    },
    ...props,
  });
  return button;
};
` 🖤

**Comment by sh1zicus** [comment]
That is, need to make a switch from a dark/light theme? 
There is already such a thing, but it does not fully work

https://github.com/user-attachments/assets/2b74c1ad-dffc-4618-929f-da921bdda45c

**Comment by PharmaRacist** [comment]
ik that but i wanted to implement it as quicktoggle in right sidebar

**Comment by PharmaRacist** [comment]
i want to ask you about take an inspiration from that progect i saw on unixporn called veshell can it be kinda implemented with ags ?

**Comment by sh1zicus** [comment]
> i want to ask you about take an inspiration from that progect i saw on unixporn called veshell can it be kinda implemented with ags ?

A very like on https://extensions.gnome.org/extension/3357/material-shell

I think it is possible

> ik that but i wanted to implement it as quicktoggle in right sidebar

I think this is not a necessary duplication. You just need to figure out that after changing the colors of the theme through gradience gtk, applications change colors without rebooting, it seems that will not do without crutches

**Comment by PharmaRacist** [comment]
are you interested in making such a thing in ur dotfiles as a switchable mode ?

**Comment by sh1zicus** [comment]
> are you interested in making such a thing in ur dotfiles as a switchable mode ?

No, it already exists
