### ISSUE TITLE
[query] difference between update-dots.sh and update-dots.dev.sh

### ISSUE THREAD

**Issue by nichroot** [sh1zicus/dots-hyprland#11]
basically title, im on cachyOS and want to update my setup, which one should i be using? also why like whats the difference between them, thanks!

**Comment by sh1zicus** [comment]
the usual update dots updates checks for updates from my github repository, dev version - you change something in the cloned repository and it completely changes the configs in home to those in the repository, i.e. the usual update script pulls the changes from github, and dev simply replaces the files in the config with those in the local repository, I hope it's clear explained

**Comment by sh1zicus** [comment]
it is very convenient to develop and submit changes to github in this way

**Comment by nichroot** [comment]
honestly i didn't fully understand, which one would you recommend me to use? i have the changed periodic table files in my system.. will using the dev updatedots replace them? so the normal updatedots is safe for me?

**Comment by sh1zicus** [comment]
> honestly i didn't fully understand, which one would you recommend me to use? i have the changed periodic table files in my system.. will using the dev updatedots replace them? so the normal updatedots is safe for me?

the dev script will replace all config files, and the regular one will update but not touch the user config

<details><summary>here is an explanation of the differences from AI:</summary>
Let's analyze the main differences between `update-dots.sh` and `update-dots.dev.sh`:

1. **Update Approach:**
   - `update-dots.sh`: Uses git for file updates, preserving user changes. Checks each file for modifications using MD5 checksums.
   - `update-dots.dev.sh`: Uses a more straightforward approach - removes old configs and copies new ones, preserving only excluded files.

2. **File Handling:**
   - `update-dots.sh`: 
     - Checks modified files
     - Allows choosing which files to keep
     - Handles renamed and deleted files from git
   - `update-dots.dev.sh`:
     - Simply backs up excluded files
     - Removes all old configs
     - Copies new files

3. **Interactivity:**
   - `update-dots.sh`: More interactive, asks user about various actions
   - `update-dots.dev.sh`: Minimal interactivity, just performs the update

4. **Additional Functionality:**
   - `update-dots.dev.sh`:
     - Restarts Hyprland and AGS
     - Tracks AGS loading time
     - Shows total script execution time

5. **Intended Use:**
   - `update-dots.sh`: For regular users who want to preserve their changes
   - `update-dots.dev.sh`: For development/testing when quick config updates are needed

6. **Error Handling:**
   - `update-dots.sh`: More thorough error handling, especially with git operations
   - `update-dots.dev.sh`: Simpler error handling, focused on execution speed

Overall, `update-dots.sh` is safer and more conservative in terms of preserving user settings, while `update-dots.dev.sh` is faster and more straightforward, designed for development purposes.
</details>

**Comment by nichroot** [comment]
got it, thanks!

**Comment by nichroot** [comment]
@sh1zicus should i do a git pull before using the dev update script?

**Comment by sh1zicus** [comment]
> @sh1zicus should i do a git pull before using the dev update script?

this is done by the update-dots.sh script
