### ISSUE TITLE
this isnt an issue nor feature jus shoutout for the amazing work this guy is doing totally happy for using ur dotfiles keep getting better our fellow dev 🫀

### ISSUE THREAD

**Issue by PharmaRacist** [sh1zicus/dots-hyprland#13]

**Comment by sh1zicus** [comment]
I've been writing code for too long, my eyes have already dripped, I'll rest tomorrow (probably)

![изображение](https://github.com/user-attachments/assets/092ede48-05e2-44e1-9c13-b62c26aa7a54)

**Comment by PharmaRacist** [comment]
waiting for more glory
