### ISSUE TITLE
updating made the new ags settings app russian

### ISSUE THREAD

**Issue by nichroot** [sh1zicus/dots-hyprland#14]
I just updated the dots rn using update-dots.sh and the settings app just changed its language to russian 

![image](https://github.com/user-attachments/assets/75fa7d67-dfa6-4ba4-90bc-8f6980eede8a)

**Comment by sh1zicus** [comment]
YES

**Comment by sh1zicus** [comment]
now in english
![изображение](https://github.com/user-attachments/assets/b78aa8b4-9280-4232-80b8-5e5710861441)

**Comment by nichroot** [comment]
just updated again.. still the same :(

**Comment by sh1zicus** [comment]
> just updated again.. still the same :(

I haven't put it on github yet, it's still raw.

**Comment by nichroot** [comment]
ah i see.. when will it be updated?

**Comment by sh1zicus** [comment]
> ah i see.. when will it be updated?

already
