### ISSUE TITLE
[Bug] Incorrect Path for Wallpaper rsync

### ISSUE THREAD

**Issue by KadirBalku** [sh1zicus/dots-hyprland#30]
- I have read the Usage and Troubleshooting pages of the wiki: https://sh1zicus.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro:  Arch Linux with gnome

---
## The issue

Installer has issue "rsyncing" Wallpapers folder. assuming folder is set incorrectly according to this error msg 

(*log below)

there is no assets folder in your repo. assuming correct execution should be something like "rsync -av Wallpapers/lock.jpg ....."

Just wanted to report nothing serious, i went into .cache/dots-hyprland and executed the rsync command with the correct Path and repeated the install.sh by skipping that step
<details>
<summary>Logs</summary>

```bash
 rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.3.0]
[./install.sh]: Command "rsync -av assets/wallpapers/Lock.jpg /home/classick/Pictures/Wallpapers/" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
[Tip] If a certain package is failing to install, try installing it separately in another terminal.
[Tip] If a package is conflicting with its -git version, in another terminal, install the -git one.
  r = Repeat this command (DEFAULT)
  e = Exit now
  i = Ignore this error and continue (your setup might not work correctly)
 [R/e/i]: 
```

</details>

Fix in #31

**Comment by sh1zicus** [comment]
yeah thanks
