### ISSUE TITLE
[Issue] Cant enable Translation

### ISSUE THREAD

**Issue by PharmaRacist** [sh1zicus/dots-hyprland#5]
- I have read the Usage and Troubleshooting pages of the wiki: https://sh1zicus.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: endeavouros

---
## The issue
the translation doesn't show up 
![Uploading image.png…]()

**Comment by nichroot** [comment]
hey refer #2

**Comment by PharmaRacist** [comment]
sorry it was it the userconfig all that time but it actually doesnt work doesnt recognise my lang nor translate it the drop downs in the left side bar are broken

**Comment by PharmaRacist** [comment]
IM STUPID

**Comment by nichroot** [comment]
were you able to fix it?

**Comment by sh1zicus** [comment]
fixed in 4db537b
- add default config file to install script (~/.ags/config.json)

**Comment by PharmaRacist** [comment]
actually yes by manually writing the gpt models and languages
