### ISSUE TITLE
[Feature] How do i enable other gpt models 

### ISSUE THREAD

**Issue by PharmaRacist** [sh1zicus/dots-hyprland#8]
first of all i really admire your work and i really appreciate it so keep it going 🖤
i was asking if you can drop a comment in the js file  that list all avilable gpt models

**Comment by sh1zicus** [comment]
> 
> first of all i really admire your work and i really appreciate it so keep it going 🖤
> i was asking if you can drop a comment in the js file  that list all avilable gpt models
> 

I will probably add a constructor to add new models to ags-tweaks

**Comment by PharmaRacist** [comment]
i was asking why do you make separate ags window (settings-app) when you can add the settings and toggles in the rightside or in a separate  side bar i think it will be more neat 🤍
![image](https://github.com/user-attachments/assets/cc9a5596-0a24-4b58-9bf1-3720311b6b6a)

**Comment by sh1zicus** [comment]
I have not found a working way to add live ags changes to the panel, it can only change hyprland, I think I will continue to develop a separate script on gjs.
