### ISSUE TITLE
[Feature] Switchable Bar Location 

### ISSUE THREAD

**Issue by PharmaRacist** [sh1zicus/dots-hyprland#9]
**What would you like to be added?**
can you include a switch or keybinding or option in the ags-tweaks app to switch the location of the bar top/bottom 

**How will it help**
Actually i think it looks good and add some variation in the overall shape 
it will be awesome if its in the dotfiles 
![Uploading image.png…]()
another time thx for the awesome work <3

**Comment by sh1zicus** [comment]
it sounds good, I'll add it as soon as I'm on the PC

**Comment by sh1zicus** [comment]
success 🥳  https://github.com/sh1zicus/dots-hyprland/commit/f385cff47fc97b2ecb91b89d00114ff72aa63287

**Comment by PharmaRacist** [comment]
bro ur a master 🤍

**Comment by sh1zicus** [comment]
> bro ur a master 🤍

I use AI claude 3.5 for development, I do something myself, and the ai does pretty well.

**Comment by sh1zicus** [comment]
for example, the ai does commits for me :)

**Comment by PharmaRacist** [comment]
teach me masterrrrrr 😄
